apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: jandemoecrwe
  description: provision ECS using backstage
spec:
  owner: group:default/guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jandemoecrwe
  description: provision ECS using backstage
  annotations:
     backstage.io/techdocs-ref: dir:./docs
     github.com/project-slug: prayankag/jandemoecrwe/actions    
spec:
  type: service
  owner: group:default/guests
  lifecycle: experimental
  system: jandemoecrwe
  providesApis:
    - jandemoecrwe
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jandemoecrwe
  description: provision ECS using backstage
spec:
  type: internal
  lifecycle: experimental
  owner: group:default/guests
  system: jandemoecrwe
  definition: "provision ECS using backstage"
